# Mutation effects on phenotypes.
# Top-level key is the viral clade that the mutation effects are computed relative to.
# The next key is the phenotype name.
# Then the keys are the CSV file with the data and columns with phenotypes within.
# The CSV must have columns "site", "wildtype", and "mutant."
mutation_phenotype_csvs:
  XBB.1.5:
      spike pseudovirus DMS:
        # https://www.biorxiv.org/content/10.1101/2023.11.13.566961v1
        csv: data/spike_pseudovirus_DMS_XBB.1.5.csv
        columns:
          - human sera escape
          - spike mediated entry
          - ACE2 binding
      RBD yeast-display DMS:
        # https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1011901
        # https://jbloomlab.github.io/SARS2-RBD-escape-calc/
        csv: data/yeast_RBD_DMS_XBB.1.5.csv
        columns:
          - ACE2 affinity
          - RBD expression
          - escape
      EVEscape:
        # https://www.nature.com/articles/s41586-023-06617-0
        # https://api.evescape.org/download_variant_data?curr-virus=COVID19&curr-variant-or-id=Omicron(XBB)
        csv: data/EVEscape_XBB_single_mutation_predictions.csv
        columns:
          - EVEscape
          - fitness_evol_indices
          - dissimilarity_charge_hydrophobicity
          - accessibility_wcn

# Pango clade JSON from https://github.com/corneliusroemer/pango-sequences
# Indicate a specific commit or just latest version from main
pango_json: https://raw.githubusercontent.com/corneliusroemer/pango-sequences/main/data/pango-consensus-sequences_summary.json

# Indicate clades that are (not) descendants of each of these parent clades
classify_descendants_of:
  - XBB
  - BA.2
  - BA.2.86

# Number of randomizations of each phenotype. Randomizations are performed by shuffling
# the mutation phenotype values among mutations.
n_randomizations: 10

# Output files
mutation_phenotypes_csv: results/mutation_phenotypes.csv
mutation_phenotypes_randomized_csv: results/mutation_phenotypes_randomized.csv
clade_phenotypes_csv: results/clade_phenotypes.csv
clade_phenotypes_randomized_csv: results/clade_phenotypes.csv
