name: SARS2-spike-predictor-phenos
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - altair=5.2
  - git-lfs
  - jupyterlab
  - numpy
  - openpyxl
  - pandas=2.1
  - papermill=2.4
  - python=3.11
  - ruamel.yaml=0.18
